name: CI & Publish to Verdaccio

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'

jobs:
  publish:
    name: Publish to Verdaccio
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Use NPM public registry temporarily
        run: npm config set registry https://registry.npmjs.org/

      - name: Install dependencies (optional)
        run: npm install || echo "No dependencies"

      - name: Extract version from tag
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Update package.json
        run: npm version $VERSION --no-git-tag-version

      - name: Set Verdaccio registry
        run: npm config set registry http://3.25.208.95:4873/

      - name: Authenticate with Verdaccio
        run: echo "//3.25.208.95:4873/:_authToken=${{ secrets.VERDACCIO_TOKEN }}" >> ~/.npmrc

      - name: Publish to Verdaccio
        run: npm publish --access=public