name: CI/CD - Release & Publish to Verdaccio

on:
  push:
    branches:
      - main
    tags:
      - 'v*'  # Trigger khi có tag dạng v1.0.0, v1.2.3, ...

jobs:
  release:
    name: 🔖 Release Tag
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/heads/')
    permissions:
      contents: write
      issues: write
      pull-requests: write

    steps:
      - name: 🛎 Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: 🔧 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: 🚀 Semantic Release
        uses: cycjimmy/semantic-release-action@v3
        with:
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish:
    name: 📦 Publish to Verdaccio
    needs: release
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: 🛎 Checkout Code
        uses: actions/checkout@v4

      - name: 🔧 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: http://3.25.208.95:4873

      - name: 🔐 Authenticate to Verdaccio
        run: |
          echo -e "${{ secrets.VERDACCIO_USERNAME }}\n${{ secrets.VERDACCIO_PASSWORD }}\n${{ secrets.VERDACCIO_EMAIL }}" | npm login --registry=http://3.25.208.95:4873

      - name: 📦 Publish Package
        run: |
          npm publish --registry=http://3.25.208.95:4873