name: CI & Publish to Verdaccio

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:   # ✅ Grant permissions
      contents: write
      issues: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Release
        uses: cycjimmy/semantic-release-action@v3
        with:
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish:
    name: Publish to Verdaccio
    runs-on: ubuntu-latest

    steps:
      if: github.ref_type == 'tag' && startsWith(github.ref, 'refs/tags/v')
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Use NPM public registry temporarily
        run: npm config set registry https://registry.npmjs.org/

      - name: Install dependencies (optional)
        run: npm install || echo "No dependencies"

      - name: Extract version from tag
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Update package.json
        run: npm version $VERSION --no-git-tag-version

      - name: Set Verdaccio registry
        run: npm config set registry http://3.25.208.95:4873/

      - name: Authenticate with Verdaccio
        run: echo "//3.25.208.95:4873/:_authToken=${{ secrets.VERDACCIO_TOKEN }}" >> ~/.npmrc

      - name: Publish to Verdaccio
        run: npm publish --access=public